shim:
  'i18n':
    exports: 'I18n'
  'backbone':
    exports: 'Backbone'
    deps: [ 'jquery', 'underscore' ]
  'backbone-support':
    exports: 'Support'
    deps: [ 'backbone' ]
  'backbone-relational': [ 'backbone' ]
  'jquery.timeago': [ 'jquery' ]
  'jquery_ujs': [ 'jquery' ]
  'bootstrap-dropdown': [ 'jquery' ]
  'bootstrap-button': [ 'jquery' ]
  'bootstrap-alert': [ 'jquery' ]
  'bootstrap-modal': [ 'jquery' ]
  'underscore':
    exports: '_'

map:
  '*':
    'i18n': 'adapters/i18n-adapter'
    'jquery.timeago': 'adapters/jquery.timeago-adapter'
    'jquery': 'adapters/jquery-adapter'
    'backbone': 'adapters/backbone-adapter'
  'adapters/i18n-adapter':
    'i18n': 'i18n'
  'adapters/jquery.timeago-adapter':
    'jquery.timeago': 'jquery.timeago'
  'adapters/jquery-adapter':
    'jquery': 'jquery'
  'jquery_ujs':
    'jquery': 'jquery'
  'adapters/backbone-adapter':
    'backbone': 'backbone'
  'backbone-relational':
    'backbone': 'backbone'
